import os
import time
os.system('color 0')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 1')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 2')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 3')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 4')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 5')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 6')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 7')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 8')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 9')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color A')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color B')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color C')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color D')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color E')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color F')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)
os.system('color 7')
print("hsejfisefjsilfjsioeofjilsefjl")
time.sleep(1)